#!/usr/bin/env node
/**
 * import-review.js
 *
 * Pulls reviewer comment files (exported from the in-player review drawer) into
 * the project so you can act on them. Reads one JSON file or a folder of them,
 * merges every comment into review/comments.json (de-duplicated by id), and
 * regenerates review/REVIEW-by-slide.md — comments grouped and sorted by slide,
 * each linking to the slide HTML so you can jump straight to what needs editing.
 *
 * Usage:
 *   npm run import-review                 # scans review/inbox/ for *.json
 *   npm run import-review -- <file.json>  # import one exported file
 *   npm run import-review -- <folder>     # import every *.json in a folder
 *
 * Re-running is safe: comments already imported (same id) are skipped, so you
 * can drop new exports in and re-run as reviews trickle in.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT       = path.resolve(__dirname, '..');
const REVIEW_DIR = path.join(ROOT, 'review');
const INBOX_DIR  = path.join(REVIEW_DIR, 'inbox');
const STORE      = path.join(REVIEW_DIR, 'comments.json');
const REPORT     = path.join(REVIEW_DIR, 'REVIEW-by-slide.md');

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (e) {
    console.warn(`  ! skipped (not valid JSON): ${path.relative(ROOT, file)}`);
    return null;
  }
}

// An exported file is { comments: [...] }; tolerate a bare array too.
function commentsFrom(payload) {
  if (!payload) return [];
  if (Array.isArray(payload)) return payload;
  if (Array.isArray(payload.comments)) return payload.comments;
  return [];
}

function gatherInputFiles(arg) {
  if (!arg) {
    if (!fs.existsSync(INBOX_DIR)) return [];
    return fs.readdirSync(INBOX_DIR)
      .filter(f => f.toLowerCase().endsWith('.json'))
      .map(f => path.join(INBOX_DIR, f));
  }
  const abs = path.resolve(arg);
  if (!fs.existsSync(abs)) {
    console.error(`Error: not found: ${arg}`);
    process.exit(1);
  }
  if (fs.statSync(abs).isDirectory()) {
    return fs.readdirSync(abs)
      .filter(f => f.toLowerCase().endsWith('.json'))
      .map(f => path.join(abs, f));
  }
  return [abs];
}

function loadStore() {
  if (!fs.existsSync(STORE)) return [];
  const data = readJson(STORE);
  return Array.isArray(data) ? data : commentsFrom(data);
}

function esc(s) {
  return String(s == null ? '' : s).replace(/\|/g, '\\|');
}

function buildReport(comments) {
  const sorted = comments.slice().sort((a, b) => {
    const ai = Number(a.slideIndex), bi = Number(b.slideIndex);
    if (Number.isFinite(ai) && Number.isFinite(bi) && ai !== bi) return ai - bi;
    return String(a.slideId || '').localeCompare(String(b.slideId || '')) ||
           String(a.createdAt || '').localeCompare(String(b.createdAt || ''));
  });

  // Group by slide id (preserving the sorted order)
  const groups = [];
  const byId = {};
  for (const c of sorted) {
    const key = c.slideId || '(unknown slide)';
    if (!byId[key]) { byId[key] = { id: key, title: c.slideTitle || '', items: [] }; groups.push(byId[key]); }
    byId[key].items.push(c);
    if (!byId[key].title && c.slideTitle) byId[key].title = c.slideTitle;
  }

  const title = (sorted[0] && sorted[0].courseTitle) || '';
  const lines = [];
  lines.push(`# Review Notes${title ? ' — ' + title : ''}`);
  lines.push('');
  lines.push(`_${comments.length} note(s) across ${groups.length} slide(s). Generated by \`npm run import-review\`._`);
  lines.push('');

  for (const g of groups) {
    const slideFile = `../course/slides/${g.id}.html`;
    lines.push(`## ${g.id}${g.title ? ' — ' + g.title : ''}`);
    lines.push(`[open slide](${slideFile})`);
    lines.push('');
    for (const c of g.items) {
      const who  = c.reviewer || '—';
      const when = (c.createdAt || '').slice(0, 10);
      const at   = (c.audioTime != null && c.audioTime > 0) ? ` · @${c.audioTime}s` : '';
      lines.push(`- **${esc(who)}** _(${when}${at})_`);
      for (const ln of String(c.text || '').split('\n')) {
        lines.push(`  ${esc(ln)}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ── Main ─────────────────────────────────────────────────────────────────────

console.log('Importing review notes...\n');

fs.mkdirSync(REVIEW_DIR, { recursive: true });

const inputs = gatherInputFiles(process.argv[2]);
if (!inputs.length) {
  console.log('No input files found.');
  console.log(`Drop exported *.json files into ${path.relative(ROOT, INBOX_DIR)}/ and re-run,`);
  console.log('or pass a file/folder: npm run import-review -- <path>');
  process.exit(0);
}

const store = loadStore();
const seen  = new Set(store.map(c => c.id).filter(Boolean));

let added = 0;
for (const file of inputs) {
  const incoming = commentsFrom(readJson(file));
  let fileAdded = 0;
  for (const c of incoming) {
    if (!c || typeof c !== 'object') continue;
    if (c.id && seen.has(c.id)) continue;
    if (c.id) seen.add(c.id);
    store.push(c);
    added++; fileAdded++;
  }
  console.log(`  + ${path.relative(ROOT, file)}  (${fileAdded} new, ${incoming.length} total)`);
}

fs.writeFileSync(STORE, JSON.stringify(store, null, 2), 'utf8');
fs.writeFileSync(REPORT, buildReport(store), 'utf8');

console.log('');
console.log(`Added ${added} new note(s).  Store now holds ${store.length}.`);
console.log(`  store:  ${path.relative(ROOT, STORE)}`);
console.log(`  report: ${path.relative(ROOT, REPORT)}`);
